"""Copy/format remote evidence in the local-only site, without evaluation."""
import json,shutil,re
from pathlib import Path
from markdown_it import MarkdownIt
R=Path(__file__).resolve().parents[2];S=R/'publish/tart-project1/dist';E=R/'code/results/cohd_scale_20260915';D=S/'scale-evidence';D.mkdir(exist_ok=True)
for name in ['analysis.json','web-data.json','method_lock.json','cli_audit.json','examples.json']:
 shutil.copy2(E/name,D/name)
shutil.copytree(E/'examples',D/'examples',dirs_exist_ok=True)
for stage in ['confirmation','language','dev_adapt','dev_guard','dev704']:
 for name in ['summary.json','per_image.json','lock.json']:
  if (E/stage/name).exists():shutil.copy2(E/stage/name,D/(stage+'_'+name))
md=MarkdownIt('commonmark',{'html':False}).enable('table')
for language in ['en','th']:
 source=E/('cohd-scale-20260915'+('.th' if language=='th' else '')+'.md');text=source.read_text(encoding='utf-8');(S/'documents'/f'scale.{language}.md').write_text(text,encoding='utf-8');html=re.sub(r'^<h1>.*?</h1>\s*','',md.render(text),count=1,flags=re.S);parts=re.split(r'(?=<h2(?:\s|>))',html);html=parts[0]+''.join('<section class="report-section">'+p+'</section>' for p in parts[1:]);(S/'documents'/f'scale.{language}.html').write_text(html,encoding='utf-8')
shutil.copy2(E/'cohd-scale-20260915.md',S/'documents/scale.source.md');catalog=json.loads((S/'documents/index.json').read_text(encoding='utf-8'))
if not any(d['id']=='scale' for d in catalog):catalog.append(dict(id='scale',progress=3,date='2026-09-15',title=dict(en='Small-person scale study: speed, CCTV and hat prompts',th='ปรับขนาดเพื่อคนตัวเล็ก: เวลา CCTV และคำอธิบายหมวก'),description=dict(en='Completed: 120 newly scored CCTV frames and 32 reused language cases. Improvement and remaining errors.',th='เสร็จแล้ว: CCTV ที่เพิ่งวัด 120 เฟรมและภาษาเดิม 32 กรณี ผลที่ดีขึ้นและข้อผิดพลาดที่เหลือ')))
(S/'documents/index.json').write_text(json.dumps(catalog,ensure_ascii=False,indent=2),encoding='utf-8')
p=S/'professor-view.js';js=p.read_text(encoding='utf-8');js=js.replace("'progress2-preview.json'].map","'progress2-preview.json','scale-evidence/web-data.json'].map");js=js.replace('const [comparison,cctv,runtime,previous]=presentationData;','const [comparison,cctv,runtime,previous,scalePayload]=presentationData;');marker='  <div class="doclinks"><a class="btn" href="#progress3">';js=js.replace(marker,'  ${scaleResultsPanel(scalePayload)}\n'+marker) if '${scaleResultsPanel(scalePayload)}' not in js else js
js=js.replace('Original remains the default. Sliding-window CoHD is the next experiment, not a completed result.','Original remains the default. The completed scale/crop follow-up appears in section 04.').replace('ยังใช้โมเดลเดิมเป็นค่าเริ่มต้น Sliding window ของ CoHD เป็นการทดลองถัดไป ยังไม่มีผล','ยังใช้โมเดลเดิมเป็นค่าเริ่มต้น ดูผลทดลองปรับขนาดและครอปที่เสร็จแล้วในหัวข้อ 04');p.write_text(js,encoding='utf-8')
p=S/'index.html';html=p.read_text(encoding='utf-8');html=html.replace('<script src="professor-view.js">','<script src="scale-results.js"></script><script src="professor-view.js">') if 'src="scale-results.js"' not in html else html;p.write_text(html,encoding='utf-8')
p=S/'cohd-explainer.js';js=p.read_text(encoding='utf-8').replace('Where could we improve it next?','Scale hypothesis and follow-up experiments').replace('เราจะทดลองปรับปรุงจุดไหนต่อ?','สมมติฐานเรื่องขนาดภาพและการทดลองต่อยอด').replace('First test: let the model see a larger person','Tested hypothesis: let the model see a larger person').replace('ทดลองแรก: ให้โมเดลเห็นคนในขนาดใหญ่ขึ้น','สมมติฐานที่ทดลองแล้ว: ให้โมเดลเห็นคนในขนาดใหญ่ขึ้น').replace('Not yet tested on CoHD.','Tested in section 04; read the measured trade-offs.').replace('ยังไม่ได้ทดสอบกับ CoHD','ทดลองแล้ว ดูผลและข้อแลกเปลี่ยนในหัวข้อ 04').replace('Next we will test whether preserving image scale improves recall enough to justify the added computation.','The follow-up scale experiment is now complete; section 04 shows gains and remaining language failures.').replace('ขั้นถัดไปจะทดสอบว่าการรักษาขนาดภาพช่วย recall ได้คุ้มกับเวลาที่เพิ่มหรือไม่','ขณะนี้ทดลองปรับขนาดแล้ว หัวข้อ 04 แสดงผลที่ดีขึ้นและปัญหาการเลือกตามภาษาที่ยังเหลือ');p.write_text(js,encoding='utf-8')
p=S/'portal-latest.js';js=p.read_text(encoding='utf-8').replace('Sliding-window inference has not yet been tested for CoHD.','The completed scale/crop follow-up is available in the Scale study report.').replace('ยังไม่ได้ทดสอบ sliding window กับ CoHD','ดูการทดลองปรับขนาดและครอปที่เสร็จแล้วในรายงาน Scale').replace('Next experiment — not executed','Earlier proposal — follow-up now available').replace('การทดลองถัดไป — ยังไม่ได้ทำ','ข้อเสนอเดิม — มีผลต่อยอดแล้ว');js+='\n/* The full chronological document list includes the completed scale follow-up. */\n';p.write_text(js,encoding='utf-8')
test=R/'publish/tart-project1/test-presentation.cjs';js=test.read_text(encoding='utf-8').replace("read('progress2-preview.json')]","read('progress2-preview.json'),read('scale-evidence/web-data.json')]");js=js.replace("vm.runInContext(fs.readFileSync('dist/cohd-explainer.js','utf8'),context);","vm.runInContext(fs.readFileSync('dist/scale-results.js','utf8'),context);\n vm.runInContext(fs.readFileSync('dist/cohd-explainer.js','utf8'),context);") if "readFileSync('dist/scale-results.js'" not in js else js;js=js.replace("assert(!output.includes('NaN'));","assert(output.includes('70.71%'));assert(output.includes('0.593 s'));assert(output.includes('scale-evidence/examples/'));assert(!output.includes('NaN'));");test.write_text(js,encoding='utf-8')
print('Copied scale evidence and added collapsible section 04 plus bilingual report. No publication.')
