"""Local formatting/copy only; every measured value is read from remote evidence."""
import json,shutil
from pathlib import Path
p=Path(__file__).resolve().parents[2];src=p/'code/results/rstp_attributes_20260915/diagnostic';site=p/'publish/tart-project1/dist';dest=site/'rstp-evidence'
shutil.copytree(src,dest,dirs_exist_ok=True)
for suffix in ['md','th.md']:shutil.copyfile(p/f'docs/rstp-attributes-20260915.{suffix}',dest/f'report.{suffix}')
data={k:json.loads((src/f'{k}.json').read_text()) for k in ['lock','per_query','summary']}
template=r'''<!doctype html><html lang="th"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>หมวกและเสื้อสีดำ · tart.project1</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f3f6fc;color:#172d4b;font:17px/1.65 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:24px}a{color:#1753bf}h1{font-size:clamp(26px,4vw,36px);line-height:1.3}h2{font-size:23px}p{margin:12px 0}header{display:flex;justify-content:space-between;align-items:center;gap:16px}button{font:inherit;background:white;border:1px solid #b3c6e2;border-radius:8px;padding:9px 16px;color:#17365b;cursor:pointer}button[aria-pressed=true]{background:#1854cc;color:white;border-color:#1854cc}button:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #e99d20;outline-offset:3px}.box,article,details{background:white;border:1px solid #d3deee;border-radius:14px;padding:22px;margin:20px 0}.note{border-left:5px solid #df9944}.tabs{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}table{border-collapse:collapse;width:100%;font-size:16px}th,td{text-align:left;border-bottom:1px solid #d7e1ef;padding:12px}th{background:#edf3ff}.scroll{overflow:auto}.muted{color:#546987;font-size:15px}img{display:block;width:100%;height:auto;border-radius:8px}summary{font-weight:700;cursor:pointer}.result{display:flex;flex-wrap:wrap;gap:12px;margin:12px 0}.pill{padding:6px 12px;border-radius:8px;background:#eaf1ff}.bad{background:#fff0e5;color:#813d17}article h2{margin-top:0}footer{padding:24px 0}small{font-size:14px}@media(max-width:600px){main{padding:14px}.box,article,details{padding:14px}th,td{padding:8px;font-size:14px}}@media print{button,.tabs{display:none}article{break-inside:avoid}}</style>
<main><header><a href="./#presentation">← tart.project1</a><button id="language">EN</button></header><div id="content"></div></main>
<script id="evidence" type="application/json">__DATA__</script><script>
const evidence=JSON.parse(document.getElementById('evidence').textContent);let language='th',kind='hat';const t=(th,en)=>language==='th'?th:en;const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){document.documentElement.lang=language;document.getElementById('language').textContent=language==='th'?'EN':'ไทย';const s=evidence.summary.results;
document.getElementById('content').innerHTML=`<p class="muted">PROGRESS 3 · 15 SEP 2026 · RSTPReid</p><h1>${t('เห็นคนแล้ว แต่แยกหมวกกับเสื้อดำได้หรือยัง?','A person mask — but does it follow the appearance?')}</h1><div class="box note"><strong>${t('ยังไม่ดีขึ้น: ทั้งสองรุ่นคืนมาสก์แม้คำสั่งไม่ตรง','Still unresolved: both methods return masks for mismatched prompts')}</strong><p>${t('6 ภาพครอปจาก CCTV · 6 บุคคล · 18 คำสั่งต่อรุ่น · ไม่ฝึกเพิ่ม','6 surveillance person crops · 6 identities · 18 queries per method · no training')}</p><p class="muted">${t('ทดสอบเบื้องต้นจากภาพที่ลักษณะชัดเจน ป้ายกำกับลบตรวจโดยผู้ช่วย AI ก่อนรัน ไม่ใช่ benchmark ที่มนุษย์รับรอง','Selected diagnostic; negative references were visually reviewed by the assistant before inference, not independently human-validated.')}</p></div>
<div class="box scroll"><table><thead><tr><th>${t('สิ่งที่ตรวจ','Check')}</th><th>CoHD original</th><th>Scale704</th></tr></thead><tbody>
${[['hat','positive_nonempty','positive_n',t('มีหมวก → คืนมาสก์','Hat present → nonempty')],['hat','negative_empty','negative_n',t('ไม่มีหมวก → คืนมาสก์ว่าง','Hat absent → empty')],['black_coat','positive_nonempty','positive_n',t('เสื้อคลุมดำ → คืนมาสก์','Black coat present → nonempty')],['black_coat','negative_empty','negative_n',t('ไม่ใช่เสื้อคลุมดำ → คืนมาสก์ว่าง','Black coat absent → empty')]].map(([k,a,b,label])=>`<tr><td>${label}</td><td>${s.original[k][a]}/${s.original[k][b]}</td><td>${s.scale704_guard[k][a]}/${s.scale704_guard[k][b]}</td></tr>`).join('')}
<tr><td>${t('เวลาเฉลี่ย · GPU ใช้งานร่วม','Mean latency · shared GPU')}</td><td>${s.original.mean_resident_s.toFixed(3)} s</td><td>${s.scale704_guard.mean_resident_s.toFixed(3)} s</td></tr></tbody></table><p class="muted">${t('นับผลว่าง/ไม่ว่างเท่านั้น ไม่ใช่ Mask IoU หรือคะแนนเลือกถูกคน ไม่มี native mask GT และเวลารอบนี้เทียบกับ GPU ว่างในรอบก่อนไม่ได้','Empty/nonempty output only: not mask IoU or instance-selection accuracy. No native mask GT; shared-GPU times are not comparable with earlier idle runs.')}</p></div>
<h2>${t('เปลี่ยนคำสั่ง แล้วดูภาพเดียวกัน','Change the prompt, inspect the same image')}</h2><div class="tabs" role="group" aria-label="Prompt">${[['hat',t('คนใส่หมวก','Person with hat')],['black_coat',t('เสื้อคลุมสีดำ','Black coat')],['native',t('คำบรรยายเดิม','Native caption')]].map(([k,l])=>`<button data-kind="${k}" aria-pressed="${k===kind}">${l}</button>`).join('')}</div>
${evidence.lock.samples.map((sample,i)=>{const q=evidence.lock.queries.find(x=>x.sample_index===i&&x.kind===kind);const rows=evidence.per_query.filter(x=>x.id===q.id);return `<article><h2>${i+1}. ${esc(sample.source.img_path)}</h2><p>${esc(q.prompt)}</p><div class="result"><span class="pill">${t('อ้างอิงคนหลัก: ','Main-person reference: ')}${q.expected_presence?t('ตรงคำสั่ง','matches'):t('ไม่ตรงคำสั่ง','does not match')}</span>${rows.map(r=>`<span class="pill ${r.presence_agreement?'':'bad'}">${r.method==='original'?'Original':'Scale704'}: ${r.output_nonempty?t('คืนมาสก์','nonempty'):t('ว่าง','empty')} · ${r.request_s.toFixed(3)} s</span>`).join('')}</div><a href="rstp-evidence/visuals/${q.id}.jpg" target="_blank" rel="noopener"><img src="rstp-evidence/visuals/${q.id}.jpg" loading="lazy" width="900" height="470" alt="${esc(q.prompt)} — original image, original CoHD, Scale704"></a><p class="muted">${t('ซ้าย: ภาพต้นฉบับ · กลาง: CoHD เดิม · ขวา: Scale704 · สีส้มคือผลทำนาย ขยายภาพเพื่อแสดงเท่านั้น','Left: input · middle: original · right: Scale704 · orange: prediction. Display enlargement only.')}</p></article>`}).join('')}
<details><summary>${t('ชุดข้อมูลที่เหมาะกับเรา','Relevant datasets')}</summary><p><a href="https://github.com/NjtechCVLab/RSTPReid-Dataset">RSTPReid</a> — ${t('ภาพครอปคนจาก 15 กล้อง พร้อมคำบรรยาย ดาวน์โหลดและทดลองแล้วในหน้านี้','Person crops from 15 cameras with descriptions. Downloaded and sampled here.')}</p><p><a href="https://github.com/speckean/upar_dataset">UPAR</a> — ${t('40 attributes จากหลายชุดข้อมูล เหมาะกับฝึกตัวตรวจลักษณะ ต้องใช้ภาพต้นทางแยก ยังไม่ได้ทดลอง','40 unified attributes across datasets; useful for attribute verification. Requires source images; not tested here.')}</p><p><a href="https://github.com/Dacun/Text-based-Person-Search">PRW-TBPS</a> — ${t('ภาพเต็ม + กล่องคน + คำบรรยาย ตรงกับการค้นหาคนใน CCTV มากกว่า ยังไม่ได้ดาวน์โหลดหรือทดลอง','Full images + person boxes + descriptions: closer to full-frame CCTV selection. Not downloaded or tested here.')}</p></details>
<details><summary>${t('จะปรับปรุงตรงไหนต่อ?','What should we test next?')}</summary><p>${t('หาคน → ตรวจบริเวณศีรษะ/ลำตัว → เทียบหมวก/สีเสื้อกับคำสั่ง → เลือกคนหรือปฏิเสธเมื่อไม่ตรง','Find people → inspect head/torso → verify hat/clothing against the query → select or reject.')}</p><p>${t('เป็นแนวทางที่ยังไม่ได้ทดลอง ต้องมีทั้งคำสั่งตรงและไม่ตรง แยกชุดฝึก/ทดสอบตามคนและกล้อง แล้ววัดเวลารวมทุกขั้น','Proposed, not tested. Use matched and mismatched descriptions, separate train/test identities and cameras, and time the whole pipeline.')}</p></details>
<footer><a href="rstp-evidence/report.${language==='th'?'th.':''}md">${t('รายงานฉบับเต็ม','Full report')}</a> · <a href="rstp-evidence/lock.json">${t('ข้อตกลงและคำสั่งก่อนรัน','Pre-run lock')}</a> · <a href="rstp-evidence/per_query.json">${t('ผลทุกคำสั่ง','All query results')}</a></footer>`;
document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;const y=window.scrollY;render();window.scrollTo(0,y)});}
document.getElementById('language').onclick=()=>{language=language==='th'?'en':'th';render()};render();
</script></html>'''
(site/'rstp-attributes.html').write_text(template.replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('<','\\u003c')),encoding='utf-8')
print('Wrote local RSTP comparison page with saved remote measurements.')
