"""Present completed remote scores as aligned English/Thai reports. No evaluation."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
STATIC=ROOT/'code/webapp/static'
A=STATIC/'extended-assets'
def read(name): return json.loads((A/name).read_text(encoding='utf-8'))
def pct(v): return f'{100*v:.2f}'
def interval(v): return f'[{100*v[0]:+.2f}, {100*v[1]:+.2f}]'
def main():
    data=read('data.json'); lock=data['method_lock']; development=read('development.json')
    assert len(data['items'])==180 and len(data['summary'])==9
    for lang in ('en','th'):
        def t(en,th): return th if lang=='th' else en
        out=['# '+t('Extended training-free experiment: a locked custom pipeline','การทดลองแบบไม่ฝึกน้ำหนักเพิ่มเติม: ระบบผสมที่ล็อกวิธีไว้'),'',
            t('15 September 2026. All inference and numerical evaluation ran on cenara70hx through Tailscale. This report formats saved outputs; it does not recompute predictions or scores.','15 กันยายน 2569 การอนุมานและการประเมินตัวเลขทั้งหมดทำบน cenara70hx ผ่าน Tailscale รายงานนี้จัดรูปแบบจากผลที่บันทึกไว้ ไม่ได้คำนวณผลทำนายหรือคะแนนใหม่'),'',
            '## '+t('Main result','ผลหลัก'),'',
            t('The locked primary improves the equal-weight balanced score against all three baselines, with all three adjusted intervals above zero. The large gain comes mainly from rejecting absent targets. Positive-mask IoU is numerically higher than LISA, but its interval still spans zero.','วิธีหลักที่ล็อกไว้เพิ่มคะแนนสมดุลแบบให้น้ำหนักเท่ากันเหนือโมเดลอ้างอิงทั้งสาม โดยช่วงที่ปรับแล้วทั้งสามช่วงมีขอบล่างมากกว่าศูนย์ ผลเพิ่มส่วนใหญ่มาจากการปฏิเสธเมื่อไม่มีเป้าหมาย IoU มาสก์เป้าหมายสูงกว่า LISA ในเชิงตัวเลข แต่ช่วงความเชื่อมั่นยังคร่อมศูนย์') if data['headline']['all_three_balanced_reliable'] and not data['headline']['positive_reliable'] else '', '', data['note'][lang],'',
            t('The primary method was selected before inference on these 180 images. The other custom variants are exploratory ablations; selecting a new winner from this table would require another untouched test.','วิธีหลักถูกเลือกก่อนเริ่มอนุมานบนภาพใหม่ 180 ภาพ วิธีผสมอื่นเป็นการทดลองแยกส่วนเพื่อสำรวจ หากเลือกผู้ชนะใหม่จากตารางนี้ ต้องมีชุดทดสอบใหม่ที่ยังไม่เคยใช้เพื่อยืนยันผล'),'',
            '| '+t('Method | Positive IoU (%) | No-target accuracy (%) | Balanced (%) | All-case IoU (%)','วิธี | IoU เมื่อมีเป้าหมาย (%) | ถูกต้องเมื่อไม่มีเป้าหมาย (%) | คะแนนสมดุล (%) | IoU ทุกกรณี (%)')+' |',
            '|---|---:|---:|---:|---:|']
        for m,s in data['summary'].items():
            out.append(f'| {m} | {pct(s["positive"]["mean_iou"])} | {pct(s["no_target"]["no_match_accuracy"])} | {pct(s["balanced_score"])} | {pct(s["all"]["mean_iou"])} |')
        out += ['',t('Balanced score is the unweighted mean of positive-target mean IoU and valid empty-mask accuracy on no-target cases. All-case IoU depends on this set’s 120:60 composition and is not a substitute for positive-target performance. Invalid responses receive zero credit.','คะแนนสมดุลคือค่าเฉลี่ยให้น้ำหนักเท่ากันระหว่าง IoU เฉลี่ยของกรณีมีเป้าหมายกับความแม่นยำในการคืนมาสก์ว่างอย่างถูกต้องเมื่อไม่มีเป้าหมาย ส่วน IoU รวมขึ้นกับสัดส่วน 120:60 ของชุดนี้ จึงใช้แทนคุณภาพเมื่อมีเป้าหมายไม่ได้ คำตอบที่ไม่ถูกต้องตามรูปแบบไม่ได้รับคะแนน'),'',
            '## '+t('Paired uncertainty against all three baselines','ความไม่แน่นอนของผลต่างกับโมเดลอ้างอิงทั้งสาม'),'',
            '| '+t('Baseline | Positive difference (points) | Adjusted interval | Balanced difference (points) | Adjusted interval','โมเดลอ้างอิง | ผลต่าง IoU เป้าหมาย (จุด) | ช่วงที่ปรับแล้ว | ผลต่างคะแนนสมดุล (จุด) | ช่วงที่ปรับแล้ว')+' |', '|---|---:|---|---:|---|']
        for b in ['LISA','YOLO_World_SAM','ZoomNeXt_vision_only']:
            p=data['paired'][data['primary']+'__vs__'+b]
            out.append(f'| {b} | {100*p["positive_mean_delta"]:+.2f} | {interval(p["positive_bonferroni_99_167ci"])} | {100*p["balanced_mean_delta"]:+.2f} | {interval(p["balanced_bonferroni_99_167ci"])} |')
        out += ['',t('Stratified paired image bootstrap, 10,000 draws. The 99.167% Bonferroni intervals adjust for six primary comparisons: two endpoints against three baselines. A strictly positive lower bound supports an improvement under this analysis; an interval spanning zero does not. Unadjusted 95% intervals and exploratory comparisons are available in the evidence JSON.','ใช้ bootstrap แบบจับคู่รายภาพ แยกชั้นกรณีมีและไม่มีเป้าหมาย จำนวน 10,000 ครั้ง ช่วง Bonferroni 99.167% ปรับสำหรับการเปรียบเทียบหลักหกครั้ง ได้แก่ตัวชี้วัดสองชนิดกับโมเดลอ้างอิงสามระบบ ขอบล่างมากกว่าศูนย์จึงสนับสนุนว่าดีขึ้นตามการวิเคราะห์นี้ หากช่วงคร่อมศูนย์ยังสรุปไม่ได้ ไฟล์หลักฐานมีช่วง 95% ที่ไม่ปรับและผลเปรียบเทียบเชิงสำรวจด้วย'),'',
            '## '+t('What the custom pipeline does','ระบบผสมทำงานอย่างไร'),'',
            t('The deployed primary retains LISA for expression-conditioned selection. Grounding DINO proposes people and SAM supplies candidate masks. A candidate is accepted when at least 50% of its pixels overlap LISA. If accepted candidates cover at least 80% of LISA, the method trims LISA outside their support dilated with a 15×15 elliptical kernel, then unions the accepted masks. Otherwise it uses their union with LISA. Finally, a frozen Qwen2-VL verifier examining the full scene with the LISA bounding box suppresses the output when its yes score is below 0.4. This score is a model token likelihood, not a calibrated probability of correctness.','วิธีหลักยังใช้ LISA เลือกตามข้อความ Grounding DINO เสนอบุคคลและ SAM สร้างมาสก์ผู้สมัคร รับผู้สมัครเมื่ออย่างน้อย 50% ของพิกเซลทับกับ LISA หากมาสก์ที่รับครอบคลุม LISA อย่างน้อย 80% จะตัดส่วน LISA ที่อยู่นอกบริเวณรองรับซึ่งขยายด้วยเคอร์เนลวงรี 15×15 แล้วรวมมาสก์ผู้สมัคร หากครอบคลุมไม่ถึงจะรวมผู้สมัครกับ LISA โดยตรง สุดท้ายใช้ Qwen2-VL ที่ตรึงน้ำหนักตรวจภาพเต็มพร้อมกรอบ LISA และคืนมาสก์ว่างเมื่อคะแนน yes ต่ำกว่า 0.4 คะแนนนี้เป็น likelihood ของโทเคน ไม่ใช่ความน่าจะเป็นว่าถูกต้องที่ผ่านการสอบเทียบ'),'',
            t('No model weights were updated. Thresholds and composition were selected using labeled development data, so training-free does not mean tuning-free. This is a frozen-model ensemble that requires LISA at deployment. ZoomNeXt is evaluated as a vision-only reference; YOLO-World uses SAM for masks.','ไม่มีการปรับน้ำหนักโมเดล แต่เลือกเกณฑ์และส่วนประกอบจากชุดพัฒนาที่มีคำตอบอ้างอิง ดังนั้นไม่ฝึกน้ำหนักไม่ได้แปลว่าไม่ปรับวิธีจากข้อมูล ระบบนี้เป็นการรวมโมเดลตรึงน้ำหนักและยังต้องใช้ LISA ขณะใช้งาน ZoomNeXt เป็นโมเดลอ้างอิงที่รับภาพเท่านั้น ส่วน YOLO-World ใช้ SAM สร้างมาสก์'),'',
            '## '+t('Development search and selection','การค้นหาและเลือกวิธีบนชุดพัฒนา'),'',
            t(f'Development used 90 expressions. The exported search contains {data["n_development_configurations"]:,} configuration evaluations; controls and compositions can repeat, so this is not a count of distinct models. The primary maximizes balanced score subject to positive IoU no lower than LISA and zero positive verifier rejection on development. Ties favor positive IoU, then fewer stages. These development constraints do not guarantee the same behavior on new images.',f'ใช้ข้อความชุดพัฒนา 90 กรณี ผลส่งออกมีการประเมินการตั้งค่า {data["n_development_configurations"]:,} รายการ ซึ่งอาจมีชุดควบคุมหรือส่วนประกอบซ้ำ จึงไม่ใช่จำนวนโมเดลที่แตกต่างกัน เลือกวิธีหลักจากคะแนนสมดุลสูงสุด โดยกำหนดว่า IoU เมื่อมีเป้าหมายต้องไม่ต่ำกว่า LISA และตัวตรวจสอบต้องไม่ปฏิเสธกรณีมีเป้าหมายบนชุดพัฒนา หากเท่ากันให้เลือก IoU สูงกว่าแล้วจึงเลือกขั้นตอนน้อยกว่า เงื่อนไขบนชุดพัฒนาไม่รับประกันว่าจะเป็นจริงบนภาพใหม่'),'',
            '| '+t('Search family | Configuration evaluations','กลุ่มการทดลอง | จำนวนการประเมินการตั้งค่า')+' |','|---|---:|']
        for k,v in development.items(): out.append(f'| {k} | {v["n_configurations"]} |')
        out += ['',t('The search included morphology, SAM agreement, custom boundary trimming and distance blending, grayscale guided filtering, CLIP scoring, Qwen2-VL scene/bounding-box/candidate verification, BLIP-2 verification, RexSeek object selection, explicit-person clause decomposition, conservative selection correction, and verifier combinations. RexSeek ran with NF4 quantization of language-model linear layers while excluding vision/projector/head modules; its result must not be represented as full-precision upstream performance. Candidate-based corrections did not meet the development inclusion rule. Raw trials and availability failures remain downloadable.','การค้นหารวมการปรับรูปร่างมาสก์ การตรวจความสอดคล้องกับ SAM การตัดขอบและผสมระยะห่าง การกรองตามภาพระดับเทา คะแนน CLIP การตรวจภาพเต็ม/กรอบ/ผู้สมัครด้วย Qwen2-VL การตรวจด้วย BLIP-2 การเลือกวัตถุด้วย RexSeek การแยกอนุประโยคที่ระบุบุคคลชัดเจน การแก้การเลือกแบบอนุรักษนิยม และการรวมตัวตรวจสอบ RexSeek ใช้ NF4 กับชั้นเชิงเส้นของโมเดลภาษาโดยเว้นส่วนภาพ projector และ head จึงไม่ใช่ผลแบบความละเอียดเต็มของต้นฉบับ วิธีแก้การเลือกจากผู้สมัครไม่ผ่านเกณฑ์นำเข้ารอบสุดท้ายจากชุดพัฒนา ผลทดลองดิบและข้อจำกัดการเรียกใช้ยังดาวน์โหลดได้'),'',
            '## '+t('Protocol and limits','ระเบียบการทดลองและข้อจำกัด'),'',
            t(f'The method was frozen at {lock["created_utc"]}. The test contains 180 distinct testA images: 120 positive and 60 no-target. The audit verifies image hashes, exclusion of historical project images, development separation, unchanged manifest and frozen method provenance. Public pretrained models may have encountered COCO; project-held-out is not pretraining-clean. This language-selection experiment establishes no fixed-camera CCTV generalization. No drone imagery is part of this experiment.',f'ล็อกวิธีเมื่อ {lock["created_utc"]} ชุดทดสอบมีภาพ testA ต่างกัน 180 ภาพ เป็นกรณีมีเป้าหมาย 120 และไม่มีเป้าหมาย 60 การตรวจสอบยืนยันแฮชภาพ การตัดภาพประวัติโครงการออก การแยกจากชุดพัฒนา manifest ที่ไม่เปลี่ยน และที่มาของวิธีที่ล็อกไว้ โมเดลสาธารณะอาจเคยพบ COCO ระหว่างฝึก ภาพใหม่ต่อโครงการจึงไม่ใช่ภาพที่รับรองว่าไม่เคยอยู่ในการฝึก ผลด้านการเลือกตามภาษานี้ยังไม่ยืนยันความสามารถทั่วไปบน CCTV ติดตั้งอยู่กับที่ การทดลองนี้ไม่มีภาพโดรน'),'',
            t('Coverage diagnostics count whether at least 50% of each visible person’s ground-truth pixels are predicted. They are not one-to-one instance matching. The separate development candidate audit uses maximum-cardinality one-to-one IoU matching to assess proposal availability; it does not measure deployed language selection. Model-stage timings are not complete deployment latency. The arbitrary-image CLI records its own end-to-end time including model loading.','ตัวชี้วัดการครอบคลุมนับว่าทำนายพิกเซลของบุคคลอ้างอิงแต่ละคนได้อย่างน้อย 50% หรือไม่ ไม่ใช่การจับคู่อินสแตนซ์หนึ่งต่อหนึ่ง ส่วนการตรวจผู้สมัครบนชุดพัฒนาใช้การจับคู่ IoU หนึ่งต่อหนึ่งที่ให้จำนวนคู่สูงสุดเพื่อดูว่ามีข้อเสนอวัตถุเพียงพอหรือไม่ ไม่ได้วัดการเลือกตามภาษาขณะใช้งาน เวลาแต่ละโมเดลไม่ใช่เวลาใช้งานครบระบบ CLI สำหรับภาพใหม่บันทึกเวลาตั้งแต่เริ่มรวมการโหลดโมเดลแยกต่างหาก'),'',
            '## '+t('Reproduce and inspect','เรียกใช้และตรวจหลักฐาน'),'',
            t('Run on the remote host from /home/osta/lisa-eval/code; supply an existing image path and a new output directory. This command does not require ground truth.','เรียกบนโฮสต์ระยะไกลจาก /home/osta/lisa-eval/code โดยระบุภาพที่มีอยู่และโฟลเดอร์ผลใหม่ คำสั่งนี้ไม่ต้องใช้คำตอบอ้างอิง'),'',
            '```bash','/home/osta/blip2-qformer-eval/.venv/bin/python scripts/infer_extended.py \\', '  --image /absolute/path/image.jpg --text "the person in a blue hat" \\', '  --out /absolute/path/new-output','```','']
        out += ['## '+t('Model access and proposal diagnostics','การเข้าถึงโมเดลและการตรวจผู้สมัคร'),'',t('SAM 3 was not evaluated: the actual weight-access probe returned HTTP 401 / GatedRepoError. It has no measured score in this study. RexSeek access succeeded and its quantized development experiments completed. Failed access is not evidence that a model performs poorly.','ไม่ได้ประเมิน SAM 3 เพราะการลองเข้าถึงน้ำหนักจริงตอบ HTTP 401 / GatedRepoError จึงไม่มีคะแนนที่วัดได้ในการทดลองนี้ ส่วน RexSeek เข้าถึงได้และทดลองบนชุดพัฒนาด้วยการลดความละเอียดน้ำหนักจนครบ การเข้าถึงไม่ได้ไม่ใช่หลักฐานว่าโมเดลมีคุณภาพต่ำ'),'', '| IoU | '+t('Matched development targets','เป้าหมายชุดพัฒนาที่จับคู่ได้')+' | '+t('Recall (%)','Recall (%)')+' |','|---|---:|---:|']
        for threshold,v in read('candidate_matching_diagnostic.json')['summary'].items():
            out.append(f'| {threshold} | {v["matched"]}/{v["total"]} | {pct(v["recall"])} |')
        out += ['',t('These are oracle proposal-availability diagnostics using development annotations. They suggest selection remains a bottleneck but do not establish that the deployed selector finds those matches.','ตัวเลขนี้ตรวจความพร้อมของผู้สมัครโดยอาศัยคำตอบอ้างอิงของชุดพัฒนา ชี้ว่าการเลือกยังเป็นข้อจำกัด แต่ไม่ได้ยืนยันว่าตัวเลือกที่นำไปใช้งานจะเลือกคู่เหล่านี้ได้'),'', '## '+t('Research foundations','งานวิจัยที่เป็นพื้นฐาน'),'',t('The custom composition draws on frozen expression segmentation, proposal masks, visual verification and image-guided refinement. It is an empirical engineering combination; this study makes no novelty claim.','ระบบผสมนี้อาศัยการแบ่งส่วนตามข้อความแบบตรึงน้ำหนัก มาสก์ผู้สมัคร การตรวจด้วยโมเดลภาพภาษา และการปรับขอบตามภาพ เป็นการนำองค์ประกอบมาทดลองร่วมกันเชิงวิศวกรรม งานนี้ไม่ได้อ้างความใหม่ทางวิชาการ'),'', '- [RexSeek official implementation](https://github.com/IDEA-Research/RexSeek)', '- [RexSeek paper](https://arxiv.org/html/2503.08507v1)', '- [Guided Image Filtering](https://people.csail.mit.edu/kaiming/eccv10/index.html)', '']
        if (A/'deployment_result.json').exists():
            run=read('deployment_result.json')
            out += [t(f'An end-to-end smoke run completed in {run["end_to_end_seconds"]:.1f} seconds on the recorded development image, including model loading. Expression: “{run["expression"]}”. Valid response: {run["response_valid"]}. This single run is a deployment check, not a throughput benchmark.',f'ทดสอบเรียกใช้งานครบระบบบนภาพจากชุดพัฒนาที่บันทึกไว้ ใช้เวลา {run["end_to_end_seconds"]:.1f} วินาทีรวมการโหลดโมเดล ข้อความ: “{run["expression"]}” คำตอบถูกต้องตามรูปแบบ: {run["response_valid"]} การเรียกครั้งเดียวนี้เป็นการตรวจการใช้งาน ไม่ใช่การวัดอัตราประมวลผล'),'', '[Deployment record](../extended-assets/deployment_result.json) · [Overlay](../extended-assets/deployment_overlay.png)','']
        for fn in ['comparison.json','paired.json','per_expression.json','audit.json','method_lock.json','selection_lock.json','development.json','availability.json','environment_audit.json','shape_implementation_audit.json','candidate_matching_diagnostic.json','locked_dev_reproduction.json','rexseek_quantization_audit.json','rexseek_loading.json']:
            out.append(f'- [{fn}](../extended-assets/{fn})')
        text='\n'.join(out)+'\n'
        path=ROOT/'docs/training-free-extended-20260915.md' if lang=='en' else STATIC/'documents/extended.th.md'
        path.write_text(text,encoding='utf-8')
    print('Built aligned reports from completed remote evidence.')
if __name__=='__main__': main()
