"""Local evidence copy and HTML formatting; no scientific execution."""
import json,shutil,re
from pathlib import Path
P=Path(__file__).resolve().parents[2];R=P/'code/results/region_verifier_20260915';S=P/'publish/tart-project1/dist';D=S/'region-evidence';D.mkdir(exist_ok=True)
for name in ['web-data.json','audit.json','method_lock.json','clip_source.json']:shutil.copyfile(R/name,D/name)
shutil.copytree(R/'visuals',D/'visuals',dirs_exist_ok=True)
for suffix in ['md','th.md']:shutil.copyfile(P/f'docs/region-verifier-20260915.{suffix}',D/f'report.{suffix}')
shutil.copyfile(P/'docs/region-verifier-protocol-20260915.md',D/'protocol.md')
data=json.loads((R/'web-data.json').read_text());style=re.search(r'<style>(.*?)</style>',(S/'rstp-attributes.html').read_text(encoding='utf-8'),re.S)[1]
html=r'''<!doctype html><html lang="th"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ตรวจลักษณะก่อนคืนมาสก์ · tart.project1</title><style>__STYLE__
.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.flow div{padding:15px;background:#e9f1ff;border-radius:12px}.flow b{display:block;margin-bottom:8px}select{font:inherit;padding:10px;max-width:100%;width:100%;border-radius:8px;border:1px solid #b3c6e2;background:white;color:#17365b}.good{background:#e4f5ec;color:#16593b}@media(max-width:650px){.flow{grid-template-columns:1fr 1fr}}</style><main><header><a href="./#presentation">← tart.project1</a><button id="language">EN</button></header><div id="content"></div></main><script id="evidence" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.getElementById('evidence').textContent);let lang='th',caseId='03_black_coat';const t=(th,en)=>lang==='th'?th:en;const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const methods=['original','scale704_guard','verified'];
function draw(){document.documentElement.lang=lang;document.getElementById('language').textContent=lang==='th'?'EN':'ไทย';const results=data.summary.results,metrics=data.audit.metrics;const q=data.manifest.queries.find(q=>q.id===caseId);const records=data.rows.filter(r=>r.id===caseId&&methods.includes(r.method));
document.getElementById('content').innerHTML=`<p class="muted">PROGRESS 3 · 06 · 15 SEP 2026</p><h1>${t('ตรวจลักษณะก่อนคืนมาสก์','Verify appearance before returning a mask')}</h1><div class="box note"><strong>${t('ลดการเลือกผิด แต่ยังพลาดหมวกจริง 2 กรณี','Fewer false acceptances, but two true hat cases are missed')}</strong><p>${t('ภาพใหม่ 24 ภาพ · 40 คำสั่ง · ไม่ซ้ำบุคคลชุดพัฒนา · ไม่ฝึกน้ำหนักโมเดลเพิ่ม','24 new images · 40 queries · separate identities from development · no weight training')}</p><p class="muted">${t('ตัวอย่างภาพครอป CCTV และคำตอบที่ผู้ช่วย AI ตรวจจากภาพ คะแนนว่าง/ไม่ว่าง ไม่ใช่ Mask IoU หรือผลเลือกคนในภาพเต็ม','Selected surveillance crops with assistant-reviewed references. Empty/nonempty agreement, not mask IoU or full-frame selection accuracy.')}</p></div>
<div class="flow"><div><b>1 · ${t('หาคน','Propose')}</b>Scale704<br>“all people”</div><div><b>2 · ${t('เลือกบริเวณ','Choose region')}</b>${t('หมวก: ทั้งกล่อง<br>เสื้อดำ: ลำตัว','Hat: whole box<br>Black coat: torso')}</div><div><b>3 · ${t('เทียบลักษณะ','Compare')}</b>CLIP ViT-B/32<br>${t('ตรึงน้ำหนัก','Frozen weights')}</div><div><b>4 · ${t('ตัดสิน','Decide')}</b>${t('เก็บมาสก์ / ปฏิเสธ','Keep mask / reject')}</div></div>
<div class="box scroll"><h2>${t('อะไรดีขึ้น อะไรยังพลาด','What improved, what still fails')}</h2><table><thead><tr><th>${t('กรณี','Case')}</th><th>CoHD original</th><th>Scale704</th><th>+ ${t('ตัวตรวจ','verifier')}</th></tr></thead><tbody>${[['hat','tp','positive',t('มีหมวก → คืนมาสก์','Hat present → mask')],['hat','tn','negative',t('ไม่มีหมวก → ปฏิเสธถูก','Hat absent → correct rejection')],['black_coat','tp','positive',t('เสื้อดำ → คืนมาสก์','Black coat → mask')],['black_coat','tn','negative',t('ไม่ใช่เสื้อดำ → ปฏิเสธถูก','Not black coat → correct rejection')]].map(([a,v,n,title])=>`<tr><td>${title}</td>${methods.map(m=>`<td>${results[m][a][v]}/${results[m][a][n]}</td>`).join('')}</tr>`).join('')}</tbody></table><p>${t('คำสั่งไม่ตรงแต่ยังเลือก: 25 → 4 กรณี · คนที่ควรเลือกแต่พลาด: 0 → 2 กรณี','False acceptance: 25 → 4 · Missed positives: 0 → 2')}</p><p class="muted">${t('จึงยังไม่ผ่านเป้าหมายดีขึ้นโดยไม่พลาดคนเพิ่ม เก็บโมเดลเดิมเป็นค่าเริ่มต้น','The no-extra-misses objective is not met. Original remains the default.')}</p></div>
<div class="box scroll"><h2>${t('เวลาที่เพิ่มขึ้น','Runtime tradeoff')}</h2><table><thead><tr><th>${t('งาน','Workload')}</th><th>Original</th><th>Scale704</th><th>+ ${t('ตัวตรวจ','verifier')}</th></tr></thead><tbody><tr><td>${t('ภาพครอป · 1 กล่อง','Crops · 1 candidate')}</td>${methods.map(m=>`<td>${results[m].mean_s.toFixed(3)} s</td>`).join('')}</tr><tr><td>${t('ภาพเต็ม · หลายกล่อง','Full frames · multiple candidates')}</td>${methods.map(m=>`<td>${metrics.fullframe_mean_s[m].toFixed(3)} s</td>`).join('')}</tr></tbody></table><p>${t('เพิ่มจาก Scale704 ประมาณ 4.7% สำหรับภาพครอป และ 17.0% สำหรับภาพเต็มตัวอย่าง','Approximately +4.7% over Scale704 for crops, +17.0% for sampled full frames')}</p><p class="muted">${t('GPU มีงานอื่นใช้อยู่ทุกครั้ง ไม่เทียบตรงกับเวลารอบก่อนเมื่อ GPU ว่าง ภาพเต็มมีเพียง 2 ภาพ × 2 คำสั่ง ไม่มีคะแนน appearance GT','All measurements used a shared GPU; do not compare with earlier idle times. Full-frame sample: two frames × two queries, no appearance GT.')}</p></div>
<h2>${t('ดูทั้งกรณีที่แก้ได้และกรณีที่พลาด','Inspect improvements and failures')}</h2><div class="tabs"><button data-case="03_black_coat">${t('ปฏิเสธเสื้อไม่ดำได้','Correct black-coat rejection')}</button><button data-case="08_hat">${t('ยังพลาดหมวกจริง','Missed real hat')}</button></div><label for="case">${t('เลือกได้ทุกคำสั่งที่ทดสอบ','Every tested query')}</label><select id="case">${data.manifest.queries.map(x=>`<option value="${x.id}" ${x.id===caseId?'selected':''}>${x.id} · ${x.attribute==='hat'?t('หมวก','hat'):t('เสื้อดำ','black coat')} · ${x.expected?t('มีจริง','present'):t('ไม่ตรง','absent')}</option>`).join('')}</select><article><h2>${esc(q.prompt)}</h2><p>${t('อ้างอิงคนหลัก: ','Main-person reference: ')}${q.expected?t('ตรงคำสั่ง','matches'):t('ไม่ตรงคำสั่ง','does not match')}</p><div class="result">${methods.map(m=>{const r=records.find(r=>r.method===m);return `<span class="pill ${r.nonempty===q.expected?'good':'bad'}">${m==='verified'?t('ตัวตรวจ','Verifier'):m==='original'?'Original':'Scale704'}: ${r.nonempty?t('คืนมาสก์','mask'):t('ปฏิเสธ','empty')} · ${r.request_s.toFixed(3)} s</span>`}).join('')}</div><a href="region-evidence/visuals/${q.id}.jpg" target="_blank" rel="noopener"><img src="region-evidence/visuals/${q.id}.jpg" width="1080" height="480" alt="${esc(q.prompt)}: input, original, Scale704, verifier"></a><p class="muted">${t('สีส้ม: มาสก์ทำนาย · สีฟ้า: บริเวณที่ตัวตรวจเห็น · ไม่ใช่กรอบคำตอบอ้างอิง','Orange: predicted mask · cyan: verifier input region, not ground truth')}</p>${q.id==='08_hat'?`<p class="bad">${t('กล่องจากมาสก์เริ่มต่ำกว่าหมวก ตัวตรวจจึงไม่เห็นรายละเอียดหมวกครบ เป็นข้อจำกัดของขั้นสร้างกล่อง','The proposal starts below the hat, removing evidence before verification. This is a proposal-stage limitation.')}</p>`:''}</article>
<details><summary>${t('ภาพเต็ม CCTV — ดูผลเท่านั้น','Full CCTV frames — qualitative only')}</summary>${[...new Set(data.fullframe.map(r=>r.key))].map(k=>{const rr=data.fullframe.filter(r=>r.key===k);return `<article><p>${esc(rr[0].prompt)}</p><a href="region-evidence/visuals/${k}.jpg" target="_blank" rel="noopener"><img loading="lazy" src="region-evidence/visuals/${k}.jpg" alt="Full CCTV qualitative comparison: ${esc(rr[0].prompt)}"></a></article>`}).join('')}<p>${t('ภาพเดิมที่เคยใช้แล้ว ไม่ได้ใช้พิสูจน์ความแม่นยำตามลักษณะ กล่องจากมาสก์อาจรวมหลายคนและจำกัดสูงสุด 8 กล่อง','Previously explored frames, no appearance accuracy claim. Mask components can merge people; at most eight are inspected.')}</p></details>
<details><summary>${t('สิ่งที่ทดลองและข้อจำกัด','Method and evidence limits')}</summary><p>${t('ใช้ 6 ภาพเดิมเลือกบริเวณและเกณฑ์ก่อนทดสอบภาพใหม่ หมวก: ทั้งกล่องดีกว่าศีรษะอย่างเดียวในชุดพัฒนา เสื้อดำ: ทั้งกล่องกับลำตัวเสมอกัน จึงยังไม่พิสูจน์ว่าลำตัวเหนือกว่า','Six old images selected modes and thresholds before confirmation. Whole-box hat checking beat head-only on development; whole/torso black checking tied, so torso superiority is not established.')}</p><p>${t('ภาพใหม่ไม่ซ้ำบุคคล แต่ไม่ใช่กล้องใหม่ เลือกกรณีที่ลักษณะชัดเจน คำตอบที่ก้ำกึ่งไม่นำมาคิดคะแนน ป้ายกำกับตรวจโดยผู้ช่วย AI ไม่ใช่มนุษย์อิสระ ไม่มี mask GT และไม่รับรองการเลือกจากฝูงชน','New identities, not new cameras. Ambiguous attributes were omitted. References were assistant-reviewed, not independently human-validated; no mask GT or crowd-selection validation.')}</p><p>${t('รองรับหมวกและเสื้อด้านบนสีดำเท่านั้น ยังไม่รองรับคำสั่งหลายเงื่อนไข คนที่ขั้นแรกหาไม่พบจะกู้กลับด้วยตัวตรวจนี้ไม่ได้','Supports hats and black upper clothing only, not arbitrary compound queries. Verification cannot recover missed proposals.')}</p></details>
<footer><a href="region-evidence/report.${lang==='th'?'th.':''}md">${t('รายงานเต็ม','Full report')}</a> · <a href="region-evidence/protocol.md">${t('วิธีทดลอง','Protocol')}</a> · <a href="region-evidence/web-data.json">${t('ข้อมูลผลทุกกรณี','All measured results')}</a> · <a href="rstp-attributes.html">${t('ตัวอย่างก่อนเพิ่มตัวตรวจ','Earlier diagnostic')}</a></footer>`;
document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{caseId=b.dataset.case;const y=window.scrollY;draw();window.scrollTo(0,y)});document.getElementById('case').onchange=e=>{caseId=e.target.value;const y=window.scrollY;draw();window.scrollTo(0,y)};}
document.getElementById('language').onclick=()=>{lang=lang==='th'?'en':'th';draw()};draw();</script></html>'''
(S/'region-verifier.html').write_text(html.replace('__STYLE__',style).replace('__DATA__',json.dumps(data,ensure_ascii=False).replace('<','\\u003c')),encoding='utf-8')
print('Saved local verifier results page.')
