"""Display remote-scored training-free artifacts; performs no evaluation."""
import json, shutil
from pathlib import Path
R=Path(__file__).resolve().parents[1]; S=R/'webapp/static'; A=S/'training-free-assets'; A.mkdir(exist_ok=True)
F=R/'results/training_free_fresh_20260914'; G=R/'results/global_local_fresh_20260914'
def read(p): return json.loads(p.read_text())
def asset(p,n):
    shutil.copy2(p,A/n)
    return 'training-free-assets/'+n
def local(p): return R/str(p).replace('/home/osta/lisa-eval/code/','')
folders={'LISA':F/'p1_masks','LISA_fill_holes':F/'fill_holes/masks','LISA_proposal_agreement':F/'agreement/masks','CLIP_global_local_selected':G/'selected/masks','YOLO_World_SAM':F/'yolo/p3_expression/masks','ZoomNeXt_vision_only':F/'zoom/masks'}
summary=read(F/'scores/comparison.json'); rows=read(F/'scores/per_expression.json'); items=[]
for i in read(F/'manifest.json')['items']:
    stem=i['item_id']+'__'+i['prompt_id']; preds={}
    for v,folder in folders.items():
        row=next(r for r in rows if r['key']==i['key'] and r['variant']==v)
        preds[v]={**row,'src':asset(folder/(stem+'.png'),stem+'_'+v+'.png')}
    items.append(dict(expression=i['expression'],case_type=i['case_type'],image=asset(local(i['image']),stem+'.jpg'),gt=asset(local(i['ground_truth']),stem+'_gt.png'),predictions=preds))
for name in ['comparison','paired','audit','per_expression','candidate_diagnostic']:
    asset(F/'scores'/f'{name}.json',name+'.json')
asset(F/'selection_lock.json','selection_lock.json')
asset(R.parent/'docs/training-free-study-20260914.md','research.md')
asset(R.parent/'docs/surveillance-research-roadmap-20260914.md','surveillance-roadmap.md')
asset(R/'results/surveillance_data_audit_20260914/split_audit.json','camouflage-split-audit.json')
data=dict(summary=summary,paired=read(F/'scores/paired.json'),diagnostic=read(F/'scores/candidate_diagnostic.json')['summary'],items=items)
html='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Training-free study · KMITL</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5ef;color:#183239;font:16px/1.6 system-ui}main{max-width:1280px;margin:auto;padding:28px 24px 64px}a{color:#006d70}h1{font:600 clamp(34px,5vw,58px)/1.1 Georgia,serif;max-width:950px}h2{font:600 28px Georgia,serif;margin-top:36px}.eyebrow{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#006d70}.notice{padding:18px;background:#fff0d3;border-left:4px solid #aa7926}.flow{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}.flow div{flex:1;min-width:220px;background:white;border:1px solid #bbccc4;padding:18px;border-radius:8px}.flow b{display:block}.muted{color:#566e6d}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;background:white;font-size:14px}td,th{padding:11px;border-bottom:1px solid #d5ded8;text-align:right;white-space:nowrap}td:first-child,th:first-child{text-align:left}th{background:#e0ebe5}.highlight{background:#e3f1e8}.controls{display:flex;gap:16px;flex-wrap:wrap;margin:20px 0}label{display:flex;flex-direction:column;flex:1;min-width:220px;font-size:13px;font-weight:600}select{padding:10px;font:inherit;background:white;border:1px solid #8fa7a6;border-radius:4px}.views{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}figure{margin:0;padding:10px;background:#e2eae5;border-radius:6px}figcaption{font-size:13px;margin-bottom:6px}img{display:block;width:100%;height:270px;object-fit:contain;background:#17292e}.prompt{font-size:21px;font-weight:650}details{padding:16px;background:white;margin:16px 0}summary{cursor:pointer;font-weight:600}footer{border-top:1px solid #afc1b8;margin-top:40px;padding-top:18px;font-size:13px}@media(max-width:850px){.views{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.views{grid-template-columns:1fr}main{padding:20px 16px}}</style>
<main><a href="attribute-research.html">← Research experiments</a><p class="eyebrow">KMITL CE69-27 · 14 September 2026 · Frozen model weights</p><h1>Training-free person segmentation, tested on 60 new images</h1><p>One image + one description → a mask of the matching person or people. Compare semantic selection, mask refinement, and no-match behavior using the same ground truth.</p>
<div class="notice"><b>New to this project's experiments, not guaranteed unseen during pretraining.</b> This locked gRefCOCO testA subset excludes 300 historical image IDs. It has 20 single-person, 20 multi-person and 20 no-target expressions. Every image has at least two annotated people. Rules were selected on old development images before scoring this set.</div>
<div class="flow"><div><b>Semantic reference</b>LISA reads the full expression and predicts a mask.</div><div><b>Training-free refinement</b>Generic person proposals → SAM masks → agreement with LISA → enclosed-hole filling.</div><div><b>Independent selection control</b>Frozen CLIP compares local appearance, scene context and explicit horizontal position.</div></div>
<h2>Measured accuracy</h2><p class="muted">All values below are percentages. Positive mean IoU is the primary metric. Overall mean IoU includes no-target cases. A valid empty prediction earns 100% on a no-target case; invalid LISA responses earn zero.</p><div class="tablewrap"><table><thead><tr><th>System</th><th>Positive IoU</th><th>Single</th><th>Multiple</th><th>Overall IoU</th><th>No-target rejection</th></tr></thead><tbody id="scores"></tbody></table></div>
<h2>Does refinement improve LISA?</h2><div id="intervals"></div><p class="muted">Paired bootstrap: 5,000 resamples of the 40 positive images. An interval crossing zero does not establish a reliable improvement. Boundary changes alone do not establish better clothing-based identity selection.</p>
<h2>Inspect every prediction</h2><div class="controls"><label>Expression<select id="expression"></select></label><label>Comparison mask<select id="method"></select></label></div><p class="prompt" id="prompt"></p><p class="muted" id="detail"></p><div class="views"><figure><figcaption>Image</figcaption><img id="im" alt="Original image"></figure><figure><figcaption>Ground truth</figcaption><img id="gt" alt="Ground-truth target mask"></figure><figure><figcaption>LISA baseline</figcaption><img id="lisa" alt="LISA prediction"></figure><figure><figcaption id="chosen">Selected method</figcaption><img id="pred" alt="Comparison prediction"></figure></div>
<details><summary>Research behind the changes</summary><p><a href="https://arxiv.org/abs/2504.00356">HybridGL (CVPR 2025)</a> motivates global/local candidate evidence. <a href="https://suikei-wang.github.io/RESAnything/">RESAnything (NeurIPS 2025)</a> motivates attribute-aware proposal selection. <a href="https://arxiv.org/abs/2502.06756">SAMRefiner (ICLR 2025)</a> motivates mask refinement. <a href="https://arxiv.org/abs/2607.03869">GeoSelect (2026 preprint, aerial imagery)</a> motivates explicit geometry. These implementations are simplified project experiments, not reproductions of those papers.</p></details>
<details><summary>Controls and limits</summary><p>No weights were trained or updated. Scalar choices used the earlier 30-image development pilot. Proposal agreement uses a locked 0.75 IoU threshold; CLIP uses spatial scoring and no effective rejection floor. YOLO-World uses the full expression and SAM for masks. ZoomNeXt is a person-finetuned, vision-only control; this language-conditioned subset cannot establish broad superiority on camouflage segmentation.</p><p>All model inference and numerical evaluation ran on the remote 8 GB GPU host. Person coverage metrics in the downloadable data count a person when at least half of its visible annotation is predicted; they are not one-to-one instance matching. No new method is claimed to be faster or novel.</p></details>
<footer><a href="training-free-assets/research.md">Full study record</a> · <a href="training-free-assets/comparison.json">Scores</a> · <a href="training-free-assets/paired.json">Paired intervals</a> · <a href="training-free-assets/per_expression.json">Every prediction's metrics</a> · <a href="training-free-assets/audit.json">Audit</a> · <a href="training-free-assets/selection_lock.json">Dataset lock</a> · <a href="model-upgrade.html">Earlier learned-layer experiment</a></footer></main>
<script>const D=__DATA__,N={LISA:'LISA-7B-v1',LISA_fill_holes:'LISA + enclosed-hole filling',LISA_proposal_agreement:'LISA + proposal agreement + filling',CLIP_global_local_selected:'Frozen CLIP global/local + spatial',YOLO_World_SAM:'YOLO-World expression + SAM',ZoomNeXt_vision_only:'ZoomNeXt EffB1 (vision only)'},$=x=>document.getElementById(x),pct=x=>(100*x).toFixed(2);
for(const [v,r] of Object.entries(D.summary)){let tr=document.createElement('tr');if(v==='LISA_proposal_agreement')tr.className='highlight';[N[v],pct(r.positive.mean_iou),pct(r.single_in_crowd.mean_iou),pct(r.multi_target.mean_iou),pct(r.all.mean_iou),pct(r.no_target.no_match_accuracy)].forEach(t=>{let td=document.createElement('td');td.textContent=t;tr.append(td)});$('scores').append(tr)}
for(const v of ['LISA_fill_holes','LISA_proposal_agreement']){const p=D.paired[v],ci=p.bootstrap_95ci,el=document.createElement('p');el.textContent=N[v]+' − LISA: '+pct(p.positive_mean_delta)+' percentage points; 95% interval '+pct(ci[0])+' to '+pct(ci[1])+'. '+(ci[0]>0?'Positive improvement on this sample.':ci[1]<0?'Lower accuracy on this sample.':'A reliable improvement is not established.');$('intervals').append(el)}
D.items.forEach((i,j)=>$('expression').add(new Option(i.case_type+' · '+i.expression,j)));Object.entries(N).forEach(([k,v])=>$('method').add(new Option(v,k)));$('method').value='LISA_proposal_agreement';function show(){const i=D.items[$('expression').value],v=$('method').value,p=i.predictions[v];$('prompt').textContent='“'+i.expression+'”';$('detail').textContent=i.case_type+' · LISA IoU '+pct(i.predictions.LISA.iou)+'% · Selected IoU '+pct(p.iou)+'% · '+(p.response_valid?'Valid response':'Invalid response');$('im').src=i.image;$('gt').src=i.gt;$('lisa').src=i.predictions.LISA.src;$('pred').src=p.src;$('chosen').textContent=N[v]}$('expression').onchange=show;$('method').onchange=show;show();</script></html>'''
html=html.replace('<details><summary>Research behind the changes</summary>','<h2>Where the next improvement should focus</h2><p id="diagnostic"></p><p>Both LISA and the proposed refinement reject 0 of 20 absent-target descriptions. Target-person coverage is unchanged by refinement. This supports a boundary improvement interpretation, with language selection and rejection still unresolved.</p><p class="muted">The candidate diagnostic uses ground truth offline and allows independent best matches. It is not one-to-one AP/recall or a deployable method. No predictions were changed.</p><details><summary>Research behind the changes</summary>')
html=html.replace('</script>',"const dg=D.diagnostic;$('diagnostic').textContent=dg.targets_with_candidate_mask_iou_ge_0_5+' of '+dg.n_targets+' target people have a SAM candidate with mask IoU ≥ 0.5. For '+dg.targets_with_candidate_mask_but_clip_coverage_below_0_5+' targets, such a candidate exists but the CLIP-selected output covers less than half the target.';</script>")
html=html.replace('<footer>','<footer><p><a href="training-free-assets/surveillance-roadmap.md">Dataset and architecture research roadmap</a> · <a href="training-free-assets/camouflage-split-audit.json">Camouflage training-overlap audit</a> · <a href="training-free-assets/candidate_diagnostic.json">Candidate diagnostic</a></p>')
(S/'training-free.html').write_text(html.replace('__DATA__',json.dumps(data).replace('</','<\\/')),encoding='utf-8')
print(S/'training-free.html')
