"""Score fixed released checkpoints on the common original-resolution mask protocol."""
import hashlib,json,platform
from pathlib import Path
import numpy as np
from PIL import Image
assert platform.node()=='cenara70hx'
C=Path('/home/osta/lisa-eval/code');O=C/'results/released_checkpoints_20260915';F=C/'results/router_confirm_20260915';lock=json.loads((O/'protocol_lock.json').read_text());lock['methods']=json.loads((O/'precision_addendum.json').read_text())['methods'];assert hashlib.sha256((F/'manifest.json').read_bytes()).hexdigest()==lock['manifest_sha256'];items=json.loads((F/'manifest.json').read_text())['items'];baseline=json.loads((F/'scores/per_expression.json').read_text());rows=[dict(r,model_s=r['model_stage_seconds']) for r in baseline if r['method']=='LISA_cached']
for method in lock['methods']:
 folder=O/method;pred=[json.loads(s) for s in (folder/'rows.jsonl').read_text().splitlines()];assert len(pred)==90 and len({r['key'] for r in pred})==90;idx={r['key']:r for r in pred}
 for i in items:
  r=idx[i['key']];p=Path(r['mask']);assert hashlib.sha256(p.read_bytes()).hexdigest()==r['mask_sha256'];mask=np.asarray(Image.open(p))>0;gt=np.asarray(Image.open(i['ground_truth']))>0;assert mask.shape==gt.shape;inter=int((mask&gt).sum());union=int((mask|gt).sum());rows.append(dict(key=i['key'],method=method,positive=bool(gt.any()),case_type=i['case_type'],iou=inter/union if union else 1.,intersection=inter,union=union,predicted_pixels=int(mask.sum()),valid=True,model_s=r['model_s'],request_s=r['request_s']))
summary={};paired={};rng=np.random.default_rng(20260915);base={r['key']:r for r in rows if r['method']=='LISA_cached'}
for method in ['LISA_cached']+lock['methods']:
 rr=[r for r in rows if r['method']==method];pos=[r for r in rr if r['positive']];neg=[r for r in rr if not r['positive']];p=float(np.mean([r['iou'] for r in pos]));n=float(np.mean([r['valid'] and r['predicted_pixels']==0 for r in neg]));summary[method]=dict(n=len(rr),positive_iou=p,no_target_accuracy=n,balanced=(p+n)/2,all_mean_iou=float(np.mean([r['iou'] for r in rr])),model_s_mean=float(np.mean([r['model_s'] for r in rr])),model_s_median=float(np.median([r['model_s'] for r in rr])),model_s_mean_excluding_first=float(np.mean([r['model_s'] for r in rr[1:]])),single_iou=float(np.mean([r['iou'] for r in rr if r['case_type']=='single_in_crowd'])),multi_iou=float(np.mean([r['iou'] for r in rr if r['case_type']=='multi_target'])),positive_rejected=sum(r['predicted_pixels']==0 for r in pos),request_s_mean=float(np.mean([r['request_s'] for r in rr])) if method!='LISA_cached' else None)
 if method!='LISA_cached':
  pd=np.array([r['iou']-base[r['key']]['iou'] for r in pos]);nd=np.array([r['iou']-base[r['key']]['iou'] for r in neg]);td=np.array([base[r['key']]['model_s']-r['model_s'] for r in rr]);pb=rng.choice(pd,(10000,len(pd))).mean(1);nb=rng.choice(nd,(10000,len(nd))).mean(1);tb=rng.choice(td,(10000,len(td))).mean(1);paired[method]=dict(positive_delta=float(pd.mean()),positive_95ci=np.quantile(pb,[.025,.975]).tolist(),balanced_delta=float((pd.mean()+nd.mean())/2),balanced_95ci=np.quantile((pb+nb)/2,[.025,.975]).tolist(),seconds_saved=float(td.mean()),seconds_saved_95ci=np.quantile(tb,[.025,.975]).tolist(),interpretation='Exploratory paired bootstrap; reused set and checkpoint training differences prevent broad superiority claims')
for name,data in [('comparison',summary),('paired',paired),('per_expression',rows)]: (O/(name+'.json')).write_text(json.dumps(data,indent=2))
(O/'audit.json').write_text(json.dumps(dict(unique_images=90,positive=60,negative=30,mask_shapes_hashes_verified=True,no_fitting=True,protocol_sha256=hashlib.sha256((O/'protocol_lock.json').read_bytes()).hexdigest(),limitations=['Existing explored 90-image set','Released models trained specifically on gRefCOCO; LISA baseline is not similarly fine-tuned','Original-resolution protocol differs from paper native-resolution metrics','SSP uses float32 weights with autocast image encoding, checked against FP32 on diagnostic images','CoHD uses upstream torch attention fallback','Historical cached-LISA times on same GPU, not interleaved timing run','No CCTV generalization or clean pretraining claim']),indent=2));print(json.dumps(dict(summary=summary,paired=paired),indent=2))

